---
- name: Install nfs-common package
  become: true
  apt:
    name: nfs-common
    state: present

- name: Ensure each mount point directory exists with correct ownership
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ nfs_owner | default('root') }}"
    group: "{{ nfs_group | default('root') }}"
    mode: '0755'
  with_items: "{{ nfs_share_mounts }}"
  
- name: Mount NFS share
  become: true
  ansible.posix.mount:
    fstype: nfs
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_opts) }}"
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ nfs_share_mounts }}"
